# The URL the site will be built for
base_url = "https://samueloverington.com"
title = "Samuel Overington"
description = "A place for some of my stuff."
author = "Samuel Overington"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true
minify_html = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

taxonomies = [
    {name = "tags", feed = false}
]


[markdown.highlighting]
theme = "tokyo-night"

[extra]
# Put all your custom variables here
social_links = [
    { name = "GitHub", href = "https://github.com/overington"},
    { name = "LinkedIn", href = "https://linkedin.com/in/scoverington"},
    { name = "Mastodon", href = "https://mathstodon.xyz/@overington"},
]
