import { cn } from '@/lib/utils';
import "./globals.css"

import SiteHeader from './SiteHeader';

import { Inter } from "next/font/google"
import { ThemeProvider } from "@/components/theme-provider"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

interface RootLayoutProps {
  children: React.ReactNode
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body
        className={cn('antialiased min-h-screen', inter.className)}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <SiteHeader />
            {children}
        </ThemeProvider>
      </body>
    </html>
  )
}

// Colours:
// rose-900: #881337
// cyan-800: #155e75
// Amber-400: #fbbf24

// Dark
// stone-800: #292524
// zinc-200: #e4e4e7